using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Actions.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CultActionsBar : UIWidget
{
    public CultActionsBar()
    {
        RobustXamlLoader.Load(this);
    }
}

