using Content.Client.Computer;
using Content.Client.Salvage.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Impstation.CosmicCult.UI

{
    [GenerateTypedNameReferences]
    public sealed partial class CosmicMonumentMenu : FancyWindow
    {
        public CosmicMonumentMenu()
        {
            RobustXamlLoader.Load(this);
        }
    }
}


