using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.Mech.Ui;

[GenerateTypedNameReferences]
public sealed partial class ImpMechEquipmentControl : Control
{
    public event Action? OnRemoveButtonPressed;

    public ImpMechEquipmentControl(EntityUid entity, string itemName, Control? fragment)
    {
        RobustXamlLoader.Load(this);
        EquipmentName.SetMessage(itemName);
        EquipmentView.SetEntity(entity);
        RemoveButton.TexturePath = "/Textures/Interface/Nano/cross.svg.png";

        if (fragment != null)
        {
            Separator.Visible = true;
            CustomControlContainer.AddChild(fragment);
        }

        RemoveButton.OnPressed += _ => OnRemoveButtonPressed?.Invoke();
    }
}
