using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.GameObjects;
using Content.Shared.Pinpointer;
using Content.Client.Stylesheets;
using YamlDotNet.Core.Tokens;

namespace Content.Client._Impstation.DropPod;

[GenerateTypedNameReferences]
public sealed partial class DropPodLocationsMenu : DefaultWindow
{
    [Dependency] private readonly IStylesheetManager _styleMan = default!;
    [Dependency] private readonly IEntityManager _entManager = default!;
    public string SearchText = "";

    public Dictionary<NetEntity, string?> Beacons = new();

    public event Action<NetEntity, string>? TeleportClicked;

    public DropPodLocationsMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Stylesheet = _styleMan.SheetSyndicate;

        SearchBar.OnTextChanged += OnSearchTextChanged;
    }

    public void AddTeleportButtons()
    {
        foreach (var points in Beacons)
        {
            Beacons.TryGetValue(points.Key, out string? name);

            var dropPoint = points.Key;

            var currentButtonRef = new Button
            {
                Text = name,
                TextAlign = Label.AlignMode.Right,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                SizeFlagsStretchRatio = 1,
                MinSize = new Vector2(340, 20),
                ClipText = true,
            };

            currentButtonRef.OnPressed += _ => TeleportClicked?.Invoke(dropPoint, name ?? "unknown drop point");
            currentButtonRef.Visible = ButtonIsVisible(currentButtonRef);

            TeleportButtonContainer.AddChild(currentButtonRef);
        }
    }

    private bool ButtonIsVisible(Button button)
    {
        return string.IsNullOrEmpty(SearchText) || button.Text == null ||
               button.Text.Contains(SearchText, StringComparison.OrdinalIgnoreCase);
    }

    private void UpdateVisibleButtons()
    {
        foreach (var child in TeleportButtonContainer.Children)
        {
            if (child is Button button)
                button.Visible = ButtonIsVisible(button);
        }
    }

    public void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        SearchText = args.Text;
        UpdateVisibleButtons();
        // Very funny it's called TeleportScroll
        TeleportScroll.SetScrollValue(Vector2.Zero);
    }
}
